version: '3.8'
services:
  prac-nest:
    image: postgres:latest
    container_name: prac-nest
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: prac-nest
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
